### ISSUE TITLE
Test I2C Communication with O_RDONLY 

### ISSUE THREAD

**Issue by dorkamotorka** [UbiquityRobotics/ubiquity_motor#108]
Macro O_RDWR should be changed to O_RDONLY and tested, because we are only doing the read() call afterwards-
    O_RDWR is opening file for reading and writing
    O_RDONLY is opening file for reading

https://github.com/UbiquityRobotics/ubiquity_motor/blob/437d31cdb6ff262c01afd4769900ee93d08b0ea1/src/motor_hardware.cc#L897

**Comment by mjstn** [comment]
I have gotten around to changing the open to O_RDONLY and it functions fine.
I have not actually pushed this because my code is doing other things and is not clean enough.
