### ISSUE TITLE
Odom fudging factor

### ISSUE THREAD

**Issue by rohbotics** [UbiquityRobotics/ubiquity_motor#11]
https://github.com/UbiquityRobotics/ubiquity_motor/blob/motor_node_tests/test/motor_node_test.cc#L41

Why is this needed to work? Why 2.7?

**Comment by anfederman** [comment]
I tested the new image with the RBX1 odom_out_and_back script.  seemed to work +- 2% with an olde Magni on a bumpy floor.

**Comment by jim-v** [comment]
Tested on V5 hardware.  Linear morion of 1.15m (measured by ruler) corresponded to 1.148 reported by /odom.

**Comment by jim-v** [comment]
Wheel separation .3195m
