### ISSUE TITLE
Noetic release ubiquity_motor

### ISSUE THREAD

**Issue by rohbotics** [UbiquityRobotics/ubiquity_motor#125]
We need to test and release ubiquity_motor for noetic.

Might need to find a replacement serial library.

**Comment by anfederman** [comment]
the motor node does appear to work under Noetic, but the
test_motor_board.py script does not.  Under Python3 it just prints the menu
and terminates, under python2 it can't find the serial port. This is the
arm32 Ubuntu 20.04.

**Comment by rohbotics** [comment]
Done
