### ISSUE TITLE
No velocity published in Joint_state

### ISSUE THREAD

**Issue by davecrawley** [UbiquityRobotics/ubiquity_motor#59]
When we try to view velocity in joint_state we only get 0.0 even though the robot is clearly moving at high speed.

**Comment by mjstn** [comment]
At this time joint state position is in radians.
The ROS docs say velocity is in rad/sec.
So I have it working now and it will publish velocity in rad/sec

This actually makes sense because the joint is a rotating wheel not the robot

**Comment by mjstn** [comment]
This is fixed in **branch  fixJointStateVelocities**  and is in the review state at this time

**Comment by mjstn** [comment]
This has been merged and thus this issue is being moved to done now.

**Comment by mjstn** [comment]
This was done long ago and moving to close finally.
