### ISSUE TITLE
Investigate toolchain 4.2

### ISSUE THREAD

**Issue by rohbotics** [UbiquityRobotics/ubiquity_motor#73]
Setup for PSoC rev 4.2 build and verify the bits are compatible and operate properly.

**Comment by mjstn** [comment]
Bits were made that worked using rev 4.2 build.   We must do a lot of testing to verify nothing has been borken for this new toolchain

**Comment by mjstn** [comment]
This should be in repository  psoc_motor_conroller_firmware

**Comment by mjstn** [comment]
Because we are approaching a new platform approach this year it has been decided that there is no need to move to toolchain of 4.2 as it brings us not enough to warrant the potential risk and trouble of such a full switchover.
