### ISSUE TITLE
Firmware instructions reference missing upgrade_firmware.py

### ISSUE THREAD

**Issue by MoffKalast** [UbiquityRobotics/ubiquity_motor#79]
Firmware instructions at https://learn.ubiquityrobotics.com/firmware-upgrade reference missing script upgrade_firmware.py as it isn't packaged along with the compiled code.

The fix can be to either change the instructions to a git clone of the repository that has the script or to package the python scripts along with the compiled code.

**Comment by rohbotics** [comment]
@MoffKalast I just checked, and it looks like the script is being packaged as part of the deb. Can you explain what the error you encountered is?

**Comment by MoffKalast** [comment]
That does not seem to be the case on the magni I'm working on right now. The rosrun command lists the script as not found.

```
ubuntu@magni2:~$ roscd ubiquity_motor
ubuntu@magni2:/opt/ros/kinetic/share/ubiquity_motor$ ls
cmake  package.xml
ubuntu@magni2:/opt/ros/kinetic/share/ubiquity_motor$ ls cmake
ubiquity_motorConfig-version.cmake  ubiquity_motorConfig.cmake
```

**Comment by rohbotics** [comment]
roscd doesn't really work for binary packages, as all the components are
placed in different places.

What happens when you run `rosrun ubiquity_motor upgrade_firmware.py` ?

Rohan

**Comment by MoffKalast** [comment]
Well it looks in that very directory for some reason.

`[rosrun] Couldn't find executable named upgrade_firmware.py below /opt/ros/kinetic/share/ubiquity_motor`

**Comment by rohbotics** [comment]
Hey @MoffKalast 

I just tried this again on the 2020-02-04 image, and it `rosrun ubiquity_motor upgrade_firmware.py` runs perfectly fine.

**Comment by MoffKalast** [comment]
¯\\\_(ツ)_/¯ May have something to do with removing and reinstalling packages then. I'll look into it more sometime.
