### ISSUE TITLE
Changes to the PID config for the default image 

### ISSUE THREAD

**Issue by mmaraja** [UbiquityRobotics/ubiquity_motor#80]
Changed values of parameters for motor node.
Improved motion and reduced deviations. 
PID_P: 5000
PID_I: 7
PID_D: -110
PID_C: 1000
PID_W: 70
PID_V: 15000

**Comment by rohbotics** [comment]
Hey @mmaraja (and @davecrawley),

Are these parameters known to be good on both 6 state and non 6 state robots? Do we need a method to change the loaded PID params based on the type of motor contoller?

**Comment by davecrawley** [comment]
These parameters haven't been tested on a non-six state robot.

That said the parameters are very close to the parameters we were putting
on our non-six state robots. The key difference is the addition of the V
term - which is not available on older firmware revisions. There are a few
other subtle changes as well (for example the windowing parameter was
narrowed to optimize performance).

David

**Comment by rohbotics** [comment]
Ok, we really should test on a "v32" robot before we can make these changes the default.

**Comment by rohbotics** [comment]
I created a PR for this, but we still need to test on a v32 robot.

**Comment by mmaraja** [comment]
The test on a v32 robot is done, new values of parameters can be default.
